version: '3' 

services:
  postgresdb:
    image: postgres # 使用官方 PostgreSQL 镜像
    environment:
      POSTGRES_DB: device_management_db # 设置数据库名称
      POSTGRES_USER: root # 设置数据库用户
      POSTGRES_PASSWORD: 123456 # 设置数据库用户密码
    ports:
      - "5433:5432" # 映射端口

  clouddm:
    image: 9ca0f19b8569548fc2bba96451ea3a851438dd3dde2c054063868b4836290565 # CloudDM 镜像名，确保已经构建或存在于某个可访问的 Docker registry 中
    depends_on:
      - postgresdb # CloudDM 依赖于 postgresdb 服务
    ports:
      - "8000:8000" 
